name: Human Capital Strategies
favicon: null
layout_spectrum: 0.4235589
typography_spectrum: 0.1146617
title: Human Capital Strategies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040101'
    - '#6F6D6E'
    - '#F7FCF6'
    - '#02375E'
    - '#D7D1DF'
  brandStrength: 0.860756
  lightness: 0.4378814
  saturation: 0.4704482
  rhythmicContrast: 0.6288997
purpose: []
