layout_spectrum: 0.4235589
color:
  saturation: 0.4704482
  lightness: 0.4378814
  brandStrength: 0.860756
  brandColors:
    - '#040101'
    - '#6F6D6E'
    - '#F7FCF6'
    - '#02375E'
    - '#D7D1DF'
  rhythmicContrast: 0.6288997
typography_spectrum: 0.1146617
name: Human Capital Strategies
